version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    depends_on:
    - db
    build:
      context: .
      dockerfile: Web/Dockerfile
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "usersdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YOUR_PASSWORD"

    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  db-data: 
